package com.example.demo.Enum;

public enum Level {
  FIRST_JUNIOR_HIGH_SCHOOL,
  SECOND_JUNIOR_HIGH_SCHOOL,
  THIRD_JUNIOR_HIGH_SCHOOL,
  FIRST__HIGH_SCHOOL,
  SECOND__HIGH_SCHOOL,
  THIRD__HIGH_SCHOOL
}
